name: hoomd-DEP
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - openmpi
  - eigen
  - cmake
  - ninja
  - pybind11
  - hoomd=*=*cpu* 
  - sphinx
  - furo
  - nbsphinx
  - ipython
  - pandoc
