name: Unit test

env:
  # TODO: Set COMPONENT_NAME to the name of your Python package.
  COMPONENT_NAME: hoomdDEP

  # Most components should not modify the rest of this file. When needed, merge in updates from
  # https://github.com/glotzerlab/hoomd-component-template/

  #############################################################################################
  # HOOMD-blue version to build.
  HOOMD_BLUE_VERSION: v7.1.0
  # prevent deadlocked MPI tests from causing the job to cancel
  MPIEXEC_TIMEOUT: 3000
  # allow mpirun to execute as root in the tests
  OMPI_ALLOW_RUN_AS_ROOT: 1
  OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
  # allow openmpi to oversubscribe cores
  PRTE_MCA_rmaps_default_mapping_policy: ":oversubscribe"
  OMPI_MCA_rmaps_base_oversubscribe: "true"
  # prevent errors from mis-configured openib systems
  OMPI_MCA_btl: "vader,self"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [trunk]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_test:
    name: Build and test [${{ matrix.name }}]
    runs-on: ubuntu-24.04
    container:
      image: nvidia/cuda:12.9.2-devel-ubuntu22.04@sha256:e0203e3a0d3d02b05f4210867b973b7f48997c71bc99b994f2bd350ee60f77a1
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: 'CPU'
          enable_gpu: 'OFF'
          enable_mpi: 'OFF'
        - name: 'CPU, MPI'
          enable_gpu: 'OFF'
          enable_mpi: 'ON'
        - name: 'GPU'
          enable_gpu: 'ON'
          enable_mpi: 'OFF'
        - name: 'GPU, MPI'
          enable_gpu: 'ON'
          enable_mpi: 'ON'

    steps:
    - name: Checkout component
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        path: component
    - name: Restore cached HOOMD-blue build
      id: cache
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: install
        key: hoomd-blue-${{ env.HOOMD_BLUE_VERSION }}-${{ matrix.enable_mpi }}-gpu-${{ matrix.enable_gpu }}
    - name: Install git
      run: |
        apt-get update
        apt-get install git --yes
    - name: Checkout HOOMD-blue
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        repository: glotzerlab/hoomd-blue
        path: hoomd-blue
        submodules: true
        ref: ${{ env.HOOMD_BLUE_VERSION }}
    - name: Create Python Environment
      uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
      with:
        pixi-version: v0.69.0
        cache: false
        activate-environment: true
        manifest-path: component/pixi.toml

    - name: Configure conda environment variables
      run: |
        echo "PYTHONPATH=$GITHUB_WORKSPACE/install" >> $GITHUB_ENV

    - name: Configure HOOMD-blue
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cmake -B build-hoomd-blue -S hoomd-blue \
              -GNinja \
              -DCMAKE_BUILD_TYPE=Release \
              -DENABLE_GPU=${ENABLE_GPU} \
              -DENABLE_MPI=${ENABLE_MPI} \
              -DCUDA_ARCH_LIST="70" \
              -DBUILD_TESTING=OFF \
              -DPLUGINS="" \
              -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install
      env:
        ENABLE_GPU: ${{ matrix.enable_gpu }}
        ENABLE_MPI: ${{ matrix.enable_mpi }}
    - name: Build HOOMD-blue
      if: steps.cache.outputs.cache-hit != 'true'
      run: ninja install -j $(($(getconf _NPROCESSORS_ONLN) + 2))
      working-directory: build-hoomd-blue
    - name: Cache HOOMD-blue build
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: install
        key: hoomd-blue-${{ env.HOOMD_BLUE_VERSION }}-${{ matrix.enable_mpi }}-gpu-${{ matrix.enable_gpu }}

    - name: Configure component
      run: CMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install cmake -S component -B build-component -GNinja -DCMAKE_BUILD_TYPE=Release
    - name: Build component
      run: ninja install -j $(($(getconf _NPROCESSORS_ONLN) + 2))
      working-directory: build-component

    - name: Run pytest (serial)
      run: python3 -m pytest --pyargs hoomd.${COMPONENT_NAME} -x -v -ra --durations=0 --durations-min=0.1
    - name: Run pytest (MPI)
      if: ${{ matrix.enable_mpi == 'ON' }}
      run: mpirun -n 2 ${GITHUB_WORKSPACE}/install/hoomd/pytest/pytest-openmpi.sh --pyargs hoomd.${COMPONENT_NAME} -x -v -ra --durations=0 --durations-min=0.1 || (( cat pytest.out.1 && exit 1 ))
